FROM alpine:3

RUN delgroup ping 2>/dev/null || true && \
    delgroup dialout 2>/dev/null || true && \
    delgroup tape 2>/dev/null || true && \
    delgroup video 2>/dev/null || true && \
    apk del iputils 2>/dev/null || true && \
    apk upgrade --no-cache && apk --no-cache add \
        ca-certificates \
        tzdata \
        curl \
        su-exec && \
    printf "root:x:0:root\nnogroup:x:65533:\nnobody:x:65534:\n" > /etc/group && \
    printf "root:x:0:0:root:/root:/bin/sh\nnobody:x:65534:65534:nobody:/:/sbin/nologin\n" > /etc/passwd && \
    rm -rf /var/cache/apk/* /tmp/*

LABEL org.opencontainers.image.title="OFKM Base" \
      org.opencontainers.image.description="Minimal Alpine base for OFKM Projects" \
      org.opencontainers.image.version="1.0.0" \
      org.opencontainers.image.authors="Kyle Mendell <ksm@ofkm.us>"

CMD ["/bin/sh"]